apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nebulacb.fullname" . }}-secrets
  labels:
    {{- include "nebulacb.labels" . | nindent 4 }}
type: Opaque
data:
  source-password: {{ .Values.config.source.password | b64enc | quote }}
  target-password: {{ .Values.config.target.password | b64enc | quote }}
  auth-password: {{ .Values.auth.password | b64enc | quote }}
